package people;

public enum Relations {
    GRAND_GRANDFATHER, GRAND_GRANDMOTHER,
    GRANDFATHER, GRANDMOTHER,

    FATHER, MOTHER,
    SON, DAUGHTER,

    GRANDSON, GRANDDAUGHTER,
    GRAND_GRANDSON, GRAND_GRANDDAUGHTER,

    BROTHER, SISTER,
    UNCLE, AUNT,
    NEPHEW, NIECE,

    SPOUSE
}
